(require 'ert)
(require 'kindle-mate)

(ert-deftest kindle-mate-reset-parameters-test ()
  (let ((kindle-mate-full-clippings "x")
        (kindle-mate-book-name "y")
        (kindle-mate-book-log "z")
        (kindle-mate-book-notes "w"))
    (kindle-mate-resets-parameters)
    (should (equal kindle-mate-full-clippings ""))
    (should (equal kindle-mate-book-name ""))
    (should (equal kindle-mate-book-log ""))
    (should (equal kindle-mate-book-notes ""))))

(ert-deftest kindle-mate-get-full-clippings-test ()
  (let ((kindle-mate-clippings-path "./My Clippings.txt"))
    (should (> (length (kindle-mate-get-full-clippings)) 0))))

(ert-deftest kindle-mate-split-into-chunks-test ()
  (let ((kindle-mate-split-string "=="))
    (should (equal (kindle-mate-split-into-chunks
                    "==a==b==c==")
                   '("a" "b" "c")))))

(ert-deftest kindle-mate-split-into-book-data-test ()
  (let* ((chunk "围城 (钱钟书)\n\nlog time\n\n\n这一张文凭，仿佛有亚当、夏娃下身那片树叶的功用，可以遮羞包丑；小小一方纸能把一个人的空疏、寡陋、愚笨都掩盖起来\n")
         (result (kindle-mate-split-into-book-data chunk)))
    (should (equal (alist-get 'name result) "围城 (钱钟书)"))
    (should (equal (alist-get 'log result) "log time"))
    (should (equal (alist-get 'note result)
                   '("这一张文凭，仿佛有亚当、夏娃下身那片树叶的功用，可以遮羞包丑；小小一方纸能把一个人的空疏、寡陋、愚笨都掩盖起来"))))
  )

(ert-deftest kindle-mate-set-name-pattern-test ()
  (let* ((fuzzy-book-name "围城")
         (result (kindle-mate-set-name-pattern fuzzy-book-name))
         (answer "^[^z-a]*围城[^z-a]*$"))
    (should (equal result answer))))

(ert-deftest kindle-mate-get-real-book-name-test ()
  (let* ((pattern "^[^z-a]*围城[^z-a]*$")
         (str "围城（钱钟书）\nWhat Does It All Mean? (Thomas Nagel;)\n蛇结（弗朗索瓦·莫里亚克）")
         (result (kindle-mate-get-real-book-name pattern str))
         (answer "围城（钱钟书）"))
    (should (equal result answer))))

(ert-deftest kindle-mate-process-book-data-test ()
  (let* ((book-data '((name . "围城")
                      (log . "time")
                      (note . "note")))
         (kindle-mate-book-name "围城")
         (result (kindle-mate-process-book-data book-data))
         (answer "\n\nnote"))
    (should (equal result answer))))

(ert-deftest kindle-mate-get-target-notes-test ()
  (let* ((kindle-mate-clippings-path "./My Clippings.txt")
         (fuzzy-book-name "围城")
         (result (kindle-mate-get-target-notes fuzzy-book-name))
         (answer "\n\n我们常把自己的写作冲动误认为自己的写作才能，自以为要写就意味着会写。\n\n方鸿渐受到两面夹攻，才知道留学文凭的重要。这一张文凭，仿佛有亚当、夏娃下身那片树叶的功用，可以遮羞包丑；小小一方纸能把一个人的空疏、寡陋、愚笨都掩盖起来"))
    (should (equal result answer))
    ))
