(require 'ert)
(require 'kindle-mate)

(ert-deftest kindle-mate-reset-parameters-test ()
  (let ((kindle-mate-full-clippings "x")
        (kindle-mate-book-name "y")
        (kindle-mate-book-log "z")
        (kindle-mate-book-notes "w"))
    (kindle-mate-resets-parameters)
    (should (equal kindle-mate-full-clippings ""))
    (should (equal kindle-mate-book-name ""))
    (should (equal kindle-mate-book-log ""))
    (should (equal kindle-mate-book-notes ""))))

(ert-deftest kindle-mate-get-full-clippings-test ()
  (let ((kindle-mate-clippings-path "./My Clippings.txt"))
    (should (> (length (kindle-mate-get-full-clippings)) 0))))

(ert-deftest kindle-mate-split-into-chunks-test ()
  (let ((kindle-mate-split-string "=="))
    (should (equal (kindle-mate-split-into-chunks
                    "==a==b==c==")
                   '("a" "b" "c")))))

(ert-deftest kindle-mate-split-into-book-data-test ()
  (let* ((chunk "围城 (钱钟书)\n\nlog time\n\n\n这一张文凭，仿佛有亚当、夏娃下身那片树叶的功用，可以遮羞包丑；小小一方纸能把一个人的空疏、寡陋、愚笨都掩盖起来\n")
         (result (kindle-mate-split-into-book-data chunk)))
    (should (equal (alist-get 'name result) "围城 (钱钟书)"))
    (should (equal (alist-get 'log result) "log time"))
    (should (equal (alist-get 'note result)
                   '("这一张文凭，仿佛有亚当、夏娃下身那片树叶的功用，可以遮羞包丑；小小一方纸能把一个人的空疏、寡陋、愚笨都掩盖起来"))))
  )
